receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:3317
      http:
        endpoint: otel-collector:3318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel'
          scrape_interval: 1s
          static_configs:
            - targets: [ 'otel-collector:9201' ]

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:9201"
    # endpoint: "prometheus:9201"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  otlp:
    endpoint: tempo:3317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,otlp,jaeger]
    metrics:
      receivers: [otlp,prometheus]
      exporters: [logging,prometheus]
    logs:
      receivers: [otlp]
      exporters: [logging]