global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  # - job_name: 'otel'
  #   scrape_interval: 1s
  #   static_configs:
  #     - targets: [ 'otel-collector:9201' ]

  - job_name: 'otel-collector'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'otel-collector:8888' ]
      - targets: [ 'otel-collector:9201' ]

  - job_name: 'OpenTelemetry'
    scrape_interval: 1s
    scheme: https
    static_configs:
      - targets: ['localhost:9184']

  - job_name: 'rabbit-mq'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:15672']

  - job_name: 'catalog-service'
    scrape_interval: 3s
    scheme: https
    static_configs:
      - targets: ['localhost:7299']

  - job_name: 'inventory-service'
    scrape_interval: 4s
    scheme: https
    static_configs:
      - targets: ['localhost:7060']